<?php
	$customer = Mage::getSingleton('customer/session')->getCustomer(); 
	
	
	$allprofiles=Mage::helper('child')->getChildProfiles(Mage::getSingleton('customer/session')->getId());
		if(!empty($_GET['child'])){
			   $profile=Mage::helper('child')->getChildProfile(Mage::getSingleton('customer/session')->getId(),$_GET['child']);  
			}
			else
			{  
				$profile=$allprofiles[0];	
			}
			 
			 
?>

<div class="profile-container">
        	<div class="row">
            	<div class="my-child"> 
<div class="column twelve subsr"><h1>My child's profile</h1>
                        
                       
	<div class="first_ch">
    <?php 
	$i=0;
	foreach($allprofiles as $pr){ 
	 
		 
					$name=$pr['Name'][0];
			 
		 ?>
    <a href="<?php echo $this->getUrl('childprofile') ?>?child=<?php echo $pr['profile_id']; ?>">
    <label for="child1" class="firstlab <?php echo ((empty($_GET['child'])&&$i==0)||($pr['profile_id']==str_replace('/','',$_GET['child'])))?'active':'' ?>">
	<?php echo $name   ?></label></a> 
    <?php
	$i++;
	 } ?>
     </div>
           </div>
<form action="<?php echo $this->getUrl('childprofile/index/save/') ?>" method="post" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
    <input type="hidden" name="profile" value="<?php echo $profile['profile_id'];  ?>" />
    <div class="left_sec_rt">
    <label class="label_nentry">*child's name</label>
   <input  type="text" id="name" name="name" value="<?php echo $profile['Name'][0]  ?>"  title="First Name" maxlength="255" class="input-text required-entry input_nentry">
    </div>
    
     <div class="right_sec_rt">
    <label class="label_nentry">*boy or girl</label>
     <select name="gender" disabled id="gender"  class="input-text required-entry input_nentry">
		<option value="">boy or girl</option>
        <?php
		$gndrs=$profile['Gender'][1];
		foreach($gndrs as $gndr)
		{
			?>
            <option <?php echo $profile['Gender'][0]==$gndr['option_type_id']?'selected':'' ?> value="<?php echo $gndr['option_type_id'] ?>"><?php echo $gndr['default_title'] ?></option>
            <?php
		}
		?>
		
		 
	</select>  
    </div>
    
     <div class="left_sec_rt">
    <label class="label_nentry">*height</label>
    <select name="height" id="height"  class="input-text required-entry input_nentry">
									<option value="" selected="">height (see chart)</option>
									<?php
										$start = 33;
										$max = 100;
										
										for($i = $start; $i <= $max; $i++):
									?>
									<option <?php echo $profile['Height'][0]==$i?'selected':'' ?> value="<?php echo $i; ?>"><?php echo $i; ?>"</option>
									<?php
										endfor;
									?>
								</select> 
    </div>
    
     <div class="right_sec_rt">
    <label class="label_nentry">*weight</label>
   <input  type="text" id="weight" name="weight" value="<?php echo $profile['Weight'][0]  ?>"  title="weight" class="input-text required-entry input_nentry">
    </div>
    <div class="left_sec_rt">
    <label class="label_nentry">*top size</label>
    <select name="atop" id="atop"  class="input-text required-entry input_nentry">
		<option value="">tops</option>
		<option <?php echo $profile['Top Size'][0]==2?'selected':'' ?> value="2">2T</option>
		<option <?php echo $profile['Top Size'][0]==3?'selected':'' ?> value="3">3T</option>
		<option <?php echo $profile['Top Size'][0]==4?'selected':'' ?> value="4">4T</option>
		<option <?php echo $profile['Top Size'][0]==5?'selected':'' ?> value="5">5</option>
		<option <?php echo $profile['Top Size'][0]==6?'selected':'' ?> value="6">6</option>
		<option <?php echo $profile['Top Size'][0]==7?'selected':'' ?> value="7">7</option>
		<option <?php echo $profile['Top Size'][0]==8?'selected':'' ?> value="8">8</option>
        <option <?php echo $profile['Top Size'][0]==9?'selected':'' ?> value="9">9</option>
		<option <?php echo $profile['Top Size'][0]==10?'selected':'' ?> value="10">10</option>
		<option <?php echo $profile['Top Size'][0]==11?'selected':'' ?> value="11">11</option>
		<option <?php echo $profile['Top Size'][0]==12?'selected':'' ?> value="12">12</option>
	</select> 
    </div>
    
    <div class="right_sec_rt">
    <label class="label_nentry">*bottom size</label>
    <select name="bottom" id="bottom"  class="input-text required-entry input_nentry">
		<option value="">bottoms</option>
		<option <?php echo $profile['Bottom Size'][0]==2?'selected':'' ?> value="2">2T</option>
		<option <?php echo $profile['Bottom Size'][0]==3?'selected':'' ?> value="3">3T</option>
		<option <?php echo $profile['Bottom Size'][0]==4?'selected':'' ?> value="4">4T</option>
		<option <?php echo $profile['Bottom Size'][0]==5?'selected':'' ?> value="5">5</option>
		<option <?php echo $profile['Bottom Size'][0]==6?'selected':'' ?> value="6">6</option>
		<option <?php echo $profile['Bottom Size'][0]==7?'selected':'' ?> value="7">7</option>
		<option <?php echo $profile['Bottom Size'][0]==8?'selected':'' ?> value="8">8</option>
        <option <?php echo $profile['Bottom Size'][0]==9?'selected':'' ?> value="9">9</option>
		<option <?php echo $profile['Bottom Size'][0]==10?'selected':'' ?> value="10">10</option>
		<option <?php echo $profile['Bottom Size'][0]==11?'selected':'' ?> value="11">11</option>
		<option <?php echo $profile['Bottom Size'][0]==12?'selected':'' ?> value="12">12</option>
	</select> 
    </div>
    
    <div class="left_sec_rt">
    <label class="label_nentry">*comments</label>
   <textarea name="details" id="details" class="input_nentry3"> <?php echo $profile['Picky'][0]  ?></textarea>
    </div>
    
    <?php if($profile['Gender'][2]=='Girl'){ ?>
    <div class="right_sec_rt">
    <label class="label_nentry">*dress size</label>
    <select name="dress" id="dress"  class="input-text required-entry input_nentry">
		<option value="">dresses</option>
		<option <?php echo $profile['Dress Size'][0]==2?'selected':'' ?>  value="2">2T</option>
		<option <?php echo $profile['Dress Size'][0]==3?'selected':'' ?>  value="3">3T</option>
		<option <?php echo $profile['Dress Size'][0]==4?'selected':'' ?>  value="4">4T</option>
		<option <?php echo $profile['Dress Size'][0]==5?'selected':'' ?>  value="5">5</option>
		<option <?php echo $profile['Dress Size'][0]==6?'selected':'' ?>  value="6">6</option>
		<option <?php echo $profile['Dress Size'][0]==7?'selected':'' ?>  value="7">7</option>
		<option <?php echo $profile['Dress Size'][0]==8?'selected':'' ?>  value="8">8</option>
        <option <?php echo $profile['Dress Size'][0]==9?'selected':'' ?> value="9">9</option>
		<option <?php echo $profile['Dress Size'][0]==10?'selected':'' ?> value="10">10</option>
		<option <?php echo $profile['Dress Size'][0]==11?'selected':'' ?> value="11">11</option>
		<option <?php echo $profile['Dress Size'][0]==12?'selected':'' ?> value="12">12</option>
	</select>
   
    </div>
    <?php } ?>
     <div class="nrow2">
    
    <input type="submit" name="SUBMIT" value="SUBMIT" class="sbmt_btn">
    
    </div>
    
    
</form>
<style>
.right_sec_rt { 
   /*height: 80px;*/
}
.left_sec_rt { 
   /*height: 80px;*/
}
.my-child {
    
    margin-bottom: 50px;
}
.input_nentry {
    
    padding: 0px 10px !important;
}
</style>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    //]]>
</script></div>
            </div>
        </div>
 